apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-eks-deployment
  namespace: python-app
  labels:
    app: python-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
        - name: python-app
          image: amodsingh25/my-python-app
          ports:
            - containerPort: 5000
