apiVersion: v1
kind: Service
metadata:
  name: python-eks-service
  namespace: python-app
  labels:
    app: python-webapp
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: python-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
